name: ci

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+"
jobs:
  docker:
    env:
      USER_NAME: ${{ github.actor }}
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.output.date }}
    steps:
    
      - name: Get current date
        id: date
        run: echo "date=$(date +'%F')" >> "$GITHUB_OUTPUT"
        
      - name: Checkout
        uses: actions/checkout@v3
        
#      - name: Login to GitHub Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ env.USER_NAME }}
#          password: ${{ secrets.CR_SECRET }}
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            chicaragua/docker_hello:${{ steps.date.outputs.date }}_${{ github.run_number }}
